(function(){var a=function(a,b,e,g){for(var f=0;f<a.length;f++){if("script"==g){var k=a[f],h=b,m=e,l=document.createElement("script"),q=document.getElementsByTagName("head")[0];l.type="text/javascript";l.async=!0;c(l,h);d(l,m);l.src=k}else k=a[f],h=b,m=e,l=document.createElement("link"),q=document.getElementsByTagName("head")[0],l.type="text/css",l.rel="stylesheet",c(l,h),d(l,m),l.href=k;q.appendChild(l)}},b=function(a,b){for(var c=document.getElementsByTagName("script"==a?"script":"link"),d=0,e=
c.length;d<e;d++)if(b==("script"==a?c[d].src:c[d].href)){c[d].parentNode.removeChild(c[d]);break}},c=function(a,b){a.addEventListener("load",function p(c){b&&b(c);a.removeEventListener("load",p,"false")},!1)},d=function(a,b){a.addEventListener("error",function p(c){b&&b(c);a.removeEventListener("error",p,"false")},!1)},e=function(a){for(var b=document.getElementsByTagName("meta"),c=0,d=b.length;c<d;c++)if(b[c].getAttribute("name")==a)return b[c].getAttribute("content");return""},g=function(){jQuery&&
k&&(k=!1,a([h.bootstrapCDN,h.pjaxCDN,h.typeaheadCDN],g,f,"script"));"undefined"!==typeof jQuery&&("undefined"!==typeof jQuery.pjax&&"undefined"!==typeof jQuery.fn.emulateTransitionEnd&&"undefined"!==typeof Bloodhound)&&(function(){$.fn.launchPopOver=function(a,b){var c=this,d=$(this).data("bs.popover");"undefined"!==typeof d&&d.enabled?(d.options.placement=b.placement,d.options.title=b.title,d.options.content=b.content):$(this).popover(b);d=$(this).data("bs.popover");"undefined"!==typeof d.timeoutId&&
clearTimeout(d.timeoutId);$(this).popover("show");d.timeoutId=setTimeout(function(){$(c).popover("hide")},a)};$.fn.hasWidthOverflowed=function(){return 0<this.length?this[0].scrollWidth>this[0].clientWidth&&640<this[0].clientWidth:!1};document.getElementsByDataAttribute=function(a,b,c){var d=[];document.querySelectorAll(a).forEach(function(a){a.getAttribute(b)==c&&d.push(a)});return d};NodeList.prototype.forEach=HTMLCollection.prototype.forEach=function(a){for(var b=0,c=this.length;b<c;b++)a&&a(this[b],
b)}}(),init())},f=function(c){try{var d=c.srcElement.src,e;console.warn("Error loading CDN resource: "+d+". Loading local resource.");b("script",d);switch(d){case h.jqueryCDN:e=h.jqueryLocal;break;case h.bootstrapCDN:e=h.bootstrapLocal;break;case h.pjaxCDN:e=h.pjaxLocal;break;case h.typeaheadCDN:e=h.typeaheadLocal}a([e],g,f,"script")}catch(k){throw k;}},k=!0,h={jqueryCDN:window.location.protocol+"//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js",bootstrapCDN:window.location.protocol+"//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js",
pjaxCDN:window.location.protocol+"//cdnjs.cloudflare.com/ajax/libs/jquery.pjax/1.9.6/jquery.pjax.min.js",typeaheadCDN:window.location.protocol+"//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js",jqueryLocal:"static-assets/js/jquery-2.1.3.min.js",bootstrapLocal:"static-assets/js/bootstrap.min.js",pjaxLocal:"static-assets/js/jquery.pjax.min.js",typeaheadLocal:"static-assets/js/typeahead.bundle.min.js"},e="static-assets/css/"+("true"==e("debug")?"app.css":"all.css")+"?v="+
e("version"),m=window.location.protocol+"//netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css",l=window.location.protocol+"//fonts.googleapis.com/css?family=Roboto:400,700";a([h.jqueryCDN],g,f,"script");a([l,m,e],void 0,function(a){console.error("Error loading resource: "+a.srcElement.href);b("link",a.srcElement.href)},"link")})();var Fn=function(){};
Fn.prototype={remove:function(a,b,c){c=a.slice((c||b)+1||a.length);a.length=0>b?a.length+b:b;return a.push.apply(a,c)},takeWhile:function(a,b,c){for(var d=[],e=0,g=a.length;e<g;e++)if(c(a[e],b))d.push(a[e]);else break;return d},any:function(a,b){var c=!1;$(a).each(function(a,e){b(e)&&(c=!0)});return c},deleteCookie:function(a){this.setCookie(a,void 0,!0)},setCookie:function(a,b,c){c?document.cookie=a+"=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;":(c=new Date,c.setTime(c.getTime()+31536E7),c=
"expires="+c.toUTCString(),document.cookie=a+"="+encodeURIComponent(b)+"; "+c)},getCookie:function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return decodeURIComponent(d.substring(a.length,d.length))}return""},cookieExists:function(a){return this.getCookie(a)?!0:!1},getFromStorage:function(a){return"config"==a?localStorage?localStorage.getItem(a)?JSON.parse(localStorage.getItem(a)):[]:this.cookieExists(a)?
JSON.parse(this.getCookie(a)):[]:localStorage?localStorage.getItem(a)?JSON.parse(localStorage.getItem(a)):{}:this.cookieExists(a)?JSON.parse(this.getCookie(a)):{}},setInStorage:function(a,b){b="string"===typeof b?b:JSON.stringify(b);localStorage?(localStorage.setItem(a,b),this.cookieExists(a)?this.deleteCookie(a):void 0):this.setCookie(a,b)},brokenImage:function(a){$(a).parents(".media a").empty().append(tmpl("tmpl_ap",{}))},getBlurred:function(){document.activeElement.blur();$("input").blur()},setUserSession:function(a,
b){0!==Object.keys(JSON.parse(decodeURIComponent(atob(b)))).length&&this.setInStorage(a,b)},getUserSession:function(a){return localStorage.getItem(a)?JSON.parse(decodeURIComponent(atob(localStorage.getItem(a)))):void 0},getRedditAuthHeader:function(){var a=void 0,b=this.getUserSession("ruser"),c=b.x_ratelimit_remaining?0<parseInt(b.x_ratelimit_remaining)||0>=parseInt(b.x_ratelimit_reset)?!0:!1:!0;b&&c&&(a={Authorization:"bearer "+b.at});return a},setUserSessionAttributes:function(a,b){var c=this.getUserSession(a);
Object.keys(b).forEach(function(a){c[a]=b[a]});this.setUserSession(a,btoa(encodeURIComponent(JSON.stringify(c))))}};
function tmpl(a,b){var c=/\W/.test(a)?new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+a.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+"');}return p.join('');"):tmpl(document.getElementById(a).innerHTML);return b?c(b):c}function getPressEvent(){return window.pressType}function init(){pjx();blenddit()}
function pjx(){$(document).pjax("a[data-pjax]","#pjax-container");$(document).on("pjax:send",function(){});$(document).on("pjax:end",function(){0<$("#listsjs").length?listsjs():0<$("#blenddit").length?blenddit():($(".teams").hide(),$(".navbar-fixed-top").show(),$(".navbar-brand > .text-warning").text("kurtlocker.org"),$(".social").show(),$("html, body").removeClass("noverflow"))})}
function blenddit(){0<$("#blenddit").length&&($(".teams").show(),$(".social").hide(),$(".navbar-fixed-bottom").removeClass("hide"),$(".navbar-fixed-top").hasClass("hide")?void 0:$(".navbar-fixed-top").addClass("hide"),$('[data-toggle="tooltip"]').tooltip(),$("#reddit-results-collapse, #reddit-greeting-collapse, #reddit-modal-collapse").collapse({toggle:!1}),window.autoRefreshState=!0,bindAutoRefreshActive(),visibilityChange(),redditNames=redditNamesFn(),redditNames.initialize(),startBlending(),contentResizeEvent(),
redditSearch("#reddit-greeting-collapse",!0),redditSearch("#reddit-results-collapse"),redditSearch("#search-control-panel",!1))}
function startBlending(){var a=new Fn;a.setUserSession("ruser",redditUser);a.setUserSession("tuser",twitterUser);if(subredditURI&&threadIdURI)getThreadById(threadIdURI,function(a){"undefined"!==typeof a.data.children&&addToConfigObj(buildRedditConfigObjByThreads(a.data.children))},void 0,configObjAction);else if(subredditURI)threadsOfSubreddit(subredditURI);else if(threadIdsURI){var b=threadIdsURI.toString().split("-"),c=[];b.forEach(function(a,e){getThreadById(a,function(a){c=c.concat(a.data.children);
b.length==c.length?0!==c.length?addToConfigObj(buildRedditConfigObjByThreads(c)):void 0:void 0},function(a,d,e,h){(new Fn).remove(b,b.indexOf(h));b.length==c.length?0!==c.length?addToConfigObj(buildRedditConfigObjByThreads(c)):void 0:void 0},function(){b.length==c.length&&configObjAction()},!1,void 0,a)})}else configObjAction()}
function checkAccessToken(a){var b=new Fn,c=b.getUserSession(a),d=c?new Date>new Date(c.ex):void 0,e=$.Deferred();return"ruser"==a&&c&&d?$.ajax("/refresh-access-token").then(function(a,c,d){200==d.status&&a.access_token?(b.setUserSessionAttributes("ruser",{at:a.access_token,ex:function(){var a=new Date,b=new Date(a);b.setMinutes(a.getMinutes()+55);return b}()}),e.resolve(d,a,"").promise()):e.reject(d,a,a.statusCode).promise();return e}):c&&!d?e.resolve({},{},"pass").promise():e.reject({},{},"fail").promise()}
function redditNamesFn(){return new Bloodhound({datumTokenizer:Bloodhound.tokenizers.obj.whitespace("value"),queryTokenizer:Bloodhound.tokenizers.whitespace,remote:{rateLimitWait:0,url:"https://oauth.reddit.com/api/search_reddit_names",transport:function(a,b,c){$.when(checkAccessToken("ruser")).then(function(){var d=(new Fn).getRedditAuthHeader();d&&(a.headers=d,$.ajax(a).done(b).fail(c).always(function(a,b,c){200==c.status&&"function"===typeof c.getResponseHeader&&(new Fn).setUserSessionAttributes("ruser",
{x_ratelimit_remaining:c.getResponseHeader("x-ratelimit-remaining"),x_ratelimit_reset:c.getResponseHeader("x-ratelimit-reset")})}))},function(a,b,c){})},prepare:function(a,b){b.type="POST";b.hasContent=!0;b.data=$.param({query:a});return b},filter:function(a){var b=[];a.names&&a.names.forEach(function(a){var d={};d.value=a;b.push(d)});return b}}})}
function visibilityChange(){function a(a){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in e?"hidden"==e[a.type]?b(!1):b(!0):this[c]?b(!1):b(!0)}function b(a){window.autoRefreshState=a;autoRefresh(a);contentResizeEvent()}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",
a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a;void 0!==document[c]&&a({type:document[c]?"blur":"focus"})}
function autoRefresh(a,b){a?(new Fn).getFromStorage("config").forEach(function(a,b){0<$(".frame-content[data-column="+b+"]").length&&"undefined"===typeof window["r"+b]&&toggleRefresh(b,!0)}):(new Fn).getFromStorage("config").forEach(function(a,d){var e=0<$(".frame-content[data-column="+d+"]").length;"undefined"!==typeof b&&d==b&&e?"undefined"===typeof window["r"+d]?toggleRefresh(d,!0):void 0:e?toggleRefresh(d,!1):void 0})}
function redditSearch(a,b){$(a+" .reddit-search-input").hasClass("tt-input")||typeAheadReddit(a+" .reddit-search-input");b&&bindRedditSearch.call($(a+" .reddit-search-submit"))}
function submissionsSearchAPI(a){a.url=window.location.protocol+"//www.reddit.com/search.json?q="+encodeURIComponent(a.query)+"&restrict_sr=off&sort="+a.sorted_by+"&t="+a.links_from;genericGet(a.url,function(a,c,d,e){0<a.data.children.length?(threadResults(a,e,!1,"submissions"),bindLoadMore(a.data.after,"submissions",e,!0),copyToAllRedditSearches(e.query,e)):"object"===typeof e.errorLoc&&null!==e.errorLoc?(showFeature("#greeting"),copyToAllRedditSearches(e.query,e),0===$("#watch-threads .list-group.contain").children().length?
watchList():void 0,$("#headingOne").launchPopOver(3E3,popOverOptions("bottom","",'There were no results found for "'+e.query+'"'))):$(e.errorLoc).launchPopOver(3E3,popOverOptions("bottom","",'There were no results found for "'+e.query+'"'));e.callback&&e.callback()},void 0,void 0,!1,a.errorLoc,a)}
function subredditsSearchAPI(a){a.url=window.location.protocol+"//www.reddit.com/subreddits/search.json?q="+encodeURIComponent(a.query);genericGet(a.url,function(a,c,d,e){0<a.data.children.length?(subredditsMatching(a,e.query,!1),bindLoadMore(a.data.after,"subreddit",e,!0),copyToAllRedditSearches(e.query,e)):"object"===typeof e.errorLoc&&null!==e.errorLoc?(showFeature("#greeting"),copyToAllRedditSearches(e.query,e),0===$("#watch-threads .list-group.contain").children().length?watchList():void 0,$("#headingOne").launchPopOver(3E3,
popOverOptions("bottom","",'There were no results found for "'+e.query+'"'))):$(e.errorLoc).launchPopOver(3E3,popOverOptions("bottom","",'There were no results found for "'+e.query+'"'))},void 0,void 0,!1,a.errorLoc,a)}
function threadsOfSubreddit(a,b){var c=window.location.protocol+"//www.reddit.com/r/"+a+".json";genericGet(c,function(b,c,g,f){threadResults(b,f,!1);bindLoadMore(b.data.after,"thread",f,!0);copyToAllRedditSearches(a,f);f.callback&&f.callback()},noResults,void 0,!1,void 0,{query:a,errorLoc:this,callback:b,url:c})}
function copyToAllRedditSearches(a,b){$("#reddit-search-results .reddit-search-input.tt-input, form.reddit-search .reddit-search-input.tt-input, #control-panel-panels .reddit-search-input.tt-input").val(a);if(b&&b.errorLoc!==window&&null!==b.errorLoc){var c=b.errorLoc.parents("form"),d=c.find("input[type=radio]:checked").val(),e=c.find("select.sorted-by").val(),g=c.find("select.links-from").val();$("form.reddit-search").each(function(a,b){bindRedditSearchRadio.call($(b).find("input[type=radio][value="+
d+"]").prop("checked",!0));$(b).find("select.sorted-by option[value="+e+"]").prop("selected",!0);$(b).find("select.links-from option[value="+g+"]").prop("selected",!0)})}$("#reddit-results-collapse").collapse("hide")}
function noResults(a,b,c,d){403==a.status?($("#search-results-container .reddit-search-input.tt-input").val(d.query),window.scrollTo(0,0),$("#reddit-search-results").launchPopOver(5E3,popOverOptions("bottom","","This subreddit is private and you do not have access to view it."))):subredditsSearchAPI(d)}function subredditsMatching(a,b,c){showFeature("#search-results-container");window.scrollTo(0,0);$("#subreddit-result-title").text('Subreddits matching "'+b+'"..');buildRedditMedia(a,"t5",c)}
function threadResults(a,b,c,d){showFeature("#search-results-container");window.scrollTo(0,0);"submissions"==d?$("#subreddit-result-title").text('Submissions matching "'+b.query+'"..'):$("#subreddit-result-title").text("/r/"+b.query);buildRedditMedia(a,"t3",c)}function typeAheadReddit(a,b){$(a).typeahead(null,{name:"reddit-names",displayKey:"value",source:redditNames.ttAdapter(),limit:20}).on("typeahead:selected typeahead:autocompleted",function(){b&&b(this)})}
function configObjAction(){0<(new Fn).getFromStorage("config").length?($(".carousel-inner").children().remove(),buildConfigToUI()):(showFeature("#greeting"),watchList())}function popOverOptions(a,b,c){return{placement:a,title:b,content:c,trigger:"manual"}}
function watchList(){var a,b=(new Fn).getFromStorage("watch");Object.keys(b).length?a=b:a={subs:"nfl nba mlb nhl mls hockey soccer collegebasketball".split(" "),match:["Game Thread","Match Thread","Live Thread"]};buildWatchList(a);fetchWatchThreads(a.match)}
function fetchWatchThreads(a){$("#watch-threads .list-group.contain").children().remove();$("#watch-list-no-results").removeClass("hide");$("#watch-subreddits input").each(function(b,c){getPosts("/r/"+c.value,"","",{target:a,callback:function(b){b.data.children.forEach(function(b){a.some(function(a){return RegExp(a.toLowerCase()).test(b.data.title.toLowerCase())})&&($("#watch-list-no-results").addClass("hide"),$("#watch-threads .list-group.contain").append(buildWatchInputOrThreadHtmlString(b.data)));
fadeIn($("#watch-threads .list-group-item"),100)})}})})}function saveWatchList(){var a={};a.subs=function(){var a=[];$("#watch-subreddits .list-group.contain input").each(function(c,d){""!==d.value&&null!==d.value?a.push(d.value):""});return a}();a.match=function(){var a=[];$("#watch-matching .list-group.contain input").each(function(c,d){""!==d.value&&null!==d.value?a.push(d.value):""});return a}();(new Fn).setInStorage("watch",a)}
function contentResizeEvent(){function a(){$("#greeting").hasClass("hide")?$(".carousel-inner").css("height",window.innerHeight-53):$(".carousel-inner").removeAttr("style")}window.height=window.innerHeight;window.width=window.innerWidth;a();frame_content_height();autoRefreshOnlyActiveColumn();$(window).unbind("resize").on("resize",function(){window.height!=window.innerHeight&&(a(),frame_content_height(),window.height=window.innerHeight);window.width!=window.innerWidth&&(a(),frame_content_height(),
autoRefreshOnlyActiveColumn(),window.width=window.innerWidth)})}function autoRefreshOnlyActiveColumn(){var a=$(".item.active").data("column");$("#content-container").hasClass("hide")?autoRefresh(!1):640>=window.innerWidth?"undefined"!=typeof a&&autoRefresh(!1,a):autoRefresh(!0)}function column_options_height(a,b){var c=$(".column-options[data-column="+a+"]");c.removeAttr("style").css("max-height",c.height());frame_content_height(a,b)}
function frame_content_height(a,b){var c="undefined"!==typeof a?$(".frame-content[data-column="+a+"]"):$(".frame-content"),d=$(".carousel-inner").hasWidthOverflowed()?10:0;if("undefined"===typeof a)c.each(function(a,c){var e=$(".column-options[data-column="+a+"]").hasClass("hide")?0:$(".column-options[data-column="+a+"]").height(),e="undefined"!==typeof b?b:e;$(c).removeAttr("style").css("height",window.innerHeight-(107+e+d))});else{var e=$(".column-options[data-column="+a+"]").hasClass("hide")?0:
$(".column-options[data-column="+a+"]").height(),e="undefined"!==typeof b?b:e;c.removeAttr("style").css("height",window.innerHeight-(107+e+d))}}function launchControls(){$("#controls").modal("toggle");updateControlsView()}
function updateControlsView(){var a=new Fn,b=a.getFromStorage("config"),c=(a=a.getUserSession("ruser"))&&a.ru?1:0,d=$("[data-twitteruser]").data("twitteruser")?1:0;c?$(".reddit-account").replaceWith(tmpl("tmpl_ar",{title:a.ru})):$(".reddit-account").replaceWith(tmpl("tmpl_as",{}));$(".panel-red .huge").text(getColumnCount(b,"reddit"));$(".panel-primary .huge").text(getColumnCount(b,"twitter"));$(".panel-yellow .huge").text(c+d)}
function getColumnCount(a,b){var c=0;a.forEach(function(a){a.type==b&&c++});return c}
function addColumnToConfig(){var a=!1;(new Fn).any(".thread-controls",function(a){return null!==$(a).val()})&&(1==$(".sub-group-controls").length?$("#column-name").val($(".sub-group-controls .thread-controls option:selected").text().trim().substr(0,22)+" ..."):$("#column-name").val("My Column"),(a=updateConfigObjFromDOM(".sub-group-controls",".subreddit-controls",".thread-controls","#reddit-column .column-settings"))&&$("#reddit-column").collapse("hide"));return a}
function showColumnOption(a,b){hideAllColumnOptions(b);$(a).removeClass("hide");$(a[0].previousElementSibling).removeClass("hide")}
function showAllColumnOptions(a){$([".settings-switch[data-column="+a+"]",".manage-threads[data-column="+a+"]",".write-comment-switch[data-column="+a+"]",".refreshSwitch[data-column="+a+"]",".trash[data-column="+a+"]"].join()).removeClass("hide");$([".write-comment[data-column="+a+"]",".edit-form[data-column="+a+"]",".settings-tab[data-column="+a+"]"].join()).addClass("hide")}
function hideAllColumnOptions(a){$([".write-comment[data-column="+a+"]",".settings-switch[data-column="+a+"]",".edit-form[data-column="+a+"]",".manage-threads[data-column="+a+"]",".settings-tab[data-column="+a+"]",".write-comment-switch[data-column="+a+"]",".refreshSwitch[data-column="+a+"]",".trash[data-column="+a+"]"].join()).addClass("hide")}
function showFeature(a){hideAllFeatures();fadeIn($(a).removeClass("hide"),100);"#greeting"==a&&$(".home-button").addClass("active-feature");"#content-container"==a?(a=(new Fn).getFromStorage("config"),$("html, body").addClass("noverflow"),autoRefreshOnlyActiveColumn(),$(".columns-button").addClass("active-feature"),1<a.length?$(".carousel-control").removeClass("hide"):$(".carousel-control").addClass("hide")):$("html, body").removeClass("noverflow")}
function hideAllFeatures(){autoRefresh(!1);$("#main-loader-container, #content-container, #greeting, #search-results-container").removeClass("faded").addClass("hide");$(".home-button, .columns-button, .open-controls").removeClass("active-feature");$(".carousel-control").addClass("hide")}function setPostThreads(a,b){var c=$(a+" .post-thread"),d=$(b+" .thread-edit");c.children().remove();d.each(function(a,b){$(b).val()&&c.append($(b).find("option:selected").clone())})}
function setSettingsFromConfig(a,b){$("#column-name-column-"+a).val(b.settings.name);$("#refresh-column-"+a).val(b.settings.refreshRate);$("#limit-column-"+a).val(b.settings.limitPosts);$("#sortBy-column-"+a).val(b.settings.sortBy)}function deleteRefresh(a){clearInterval(window["r"+a]);delete window["r"+a]}
function toggleRefresh(a,b){var c="undefined"!==typeof b?$(".refreshSwitch[data-column="+a+"] i").hasClass("fa-toggle-on")&&b:$(".refreshSwitch[data-column="+a+"] i").hasClass("fa-toggle-on"),d=(new Fn).getFromStorage("config");deleteRefresh(a);c&&window.autoRefreshState?window["r"+a]=setInterval(function(){d[a]?getCommentsForColumn(d[a],a):clearInterval(window["r"+a])},1E3*parseInt(d[a].settings.refreshRate)):clearInterval(window["r"+a])}
function makeItemActive(a){$(".item").removeClass("active");$(".item[data-column="+a+"]").addClass("active")}function cacheColumn(a,b,c){a[b].cachedComments=c;(new Fn).setInStorage("config",a)}
function getCommentsForColumn(a,b,c){showLoader(b);if(c&&a.cachedComments)a.cachedComments.forEach(function(a){a[2]=b}),(a=getMergedData(a.cachedComments))&&(0===$(".frame-content[data-column="+b+"]").children().length&&0<a[1].data.children.length)&&markFirstComment(a[1].data.children[0].data.name,b),a&&displayComments(a,b),hideLoader(b);else{var d=[];c=0;for(var e=a.threads.length;c<e;c++)getPosts(a.threads[c].thread,a.settings.sortBy,a.settings.limitPosts,{target:{columnNum:b,threadNum:c},errorMsgLoc:".frame[data-column="+
b+"]",callback:function(a,c){var e=(new Fn).getFromStorage("config");d=d.concat([a.concat(c.columnNum).concat(c.threadNum)]);"undefined"!==typeof e[c.columnNum]&&e[c.columnNum].threads.length==d.length&&(cacheColumn(e,b,d),e=getMergedData(d),0===$(".frame-content[data-column="+b+"]").children().length&&0<e[1].data.children.length&&markFirstComment(e[1].data.children[0].data.name,c.columnNum),displayComments(e,c.columnNum),hideLoader(c.columnNum))}})}}
function appendColNumAndThreadNum(a,b,c){a.forEach(function(a){var e="more"!=a.kind&&a.data.replies.hasOwnProperty("data")?a.data.replies.data.children:[];a.data.name+="-"+b+"-"+c;a.data.parent_id+="-"+b+"-"+c;appendColNumAndThreadNum(e,b,c)});return a}function markFirstComment(a,b){"undefined"!==typeof a&&(window["firstComment"+b]=a)}
function updateConfigObjFromDOM(a,b,c,d,e){var g={},f={},k=[];a=$(a);d=$(d).find(".form-control");var h=!1,m="undefined"!==typeof e&&"reddit"==$(".frame-position[data-column="+e+"]").data("type")||!$("#reddit").hasClass("hide")?"reddit":"twitter",l=new Fn,n=l.getFromStorage("config");a.each(function(a,d){var e=$(d).find(c).val(),g=$(d).find(b+".tt-input").val();e&&g&&(e={},g=$(d).find(c+" option:selected"),e.subreddit=$(d).find(b+".tt-input").val(),e.thread=$(d).find(c).val(),e.threadid=g.data("threadid"),
e.threadtitle=g.data("threadtitle"),e.subid=g.data("subid"),k.push(e))});0<a.length&&(l.any(a.find(c),function(a){return null!==$(a).val()})&&l.any(a.find(b+".tt-input"),function(a){return""!==$(a).val()}))&&(g.threads=k,f.name=d[0].value,f.refreshRate=d[1].value,f.limitPosts=d[2].value,f.sortBy=d[3].value,g.settings=f,g.type=m,"undefined"!==typeof e?n[e]=g:(n=n.concat(g),h=!0),l.setInStorage("config",n));return h}
function addToConfigObj(a){var b=new Fn;b.setInStorage("config",b.getFromStorage("config").concat(a))}
function setThreads(a,b){var c="undefined"!==typeof b[2]?$($(b[0]+"[data-column="+b[2]+"]")[b[1]]):$($(b[0])[b[1]]),d=(new Fn).getFromStorage("config");c.children().remove();a.data.children.forEach(function(a){c.append(tmpl("tmpl_v",{post:a}))});0<d.length&&"undefined"!==typeof b[2]&&(d=d[b[2]].threads[b[1]],0===c.find("option[data-threadid="+d.threadid+"]").length&&d.subid==c.find("option:selected").data("subid")&&c.append(tmpl("tmpl_w",{threadObj:d})),c.find("option[data-threadid="+d.threadid+"]").prop("selected",
!0))}function showLoader(a){$(".frame-overlay[data-column="+a+"]").addClass("half-fade");$(".loading[data-column="+a+"]").removeClass("hide").addClass("faded")}function hideLoader(a){$(".frame-overlay[data-column="+a+"]").removeClass("half-fade");$(".loading[data-column="+a+"]").removeClass("faded");setTimeout(function(){$(".loading[data-column="+a+"]").addClass("hide")},500)}function fadeIn(a,b,c){setTimeout(function(){$(a).addClass(c?c:"faded")},b)}function getIcon(a){return"icon-"+a}
function updateVoteState(a,b){var c=$(".vote.up[data-id^="+b.id+"]"),d=$(".vote.down[data-id^="+b.id+"]");$(".score[data-id^="+b.id+"]").data("vote-state",b.dir);1==b.dir?(c.addClass("active"),d.removeClass("active")):-1==b.dir?(d.addClass("active"),c.removeClass("active")):(c.removeClass("active"),d.removeClass("active"))}function isRedditUserLoggedIn(){return $("[data-reddituser]").data("reddituser")?!0:!1}
function replyLevelCommentFail(a){$("#reply-textarea, #reply-save").removeAttr("disabled");$($("#reply-textarea")[0].form).launchPopOver(3E3,popOverOptions("top","","There was a problem posting your reply. Try again!"))}function topLevelCommentFail(a){var b=$(a.postPane).find("form");frame_content_height(a.columnNum);b.find(".textarea-reply").launchPopOver(3E3,popOverOptions("top","","There was a problem posting your comment. Try again!"))}
function postTopLevelComment(a,b){var c=$(b.postPane).find("form");c.find(".textarea-reply").val("").removeAttr("disabled");c.find(".save-reply").removeAttr("disabled");frame_content_height(b.columnNum);bindColumnBars.call($(".column-bars[data-column="+b.columnNum+"] > a"),b.columnNum);bindGetCommentsForColumn.call($(".frame[data-column="+b.columnNum+"] .frame-header"),b.columnNum)}
function insertReplyIntoDOM(a,b){$("#reply-textarea, #reply-save").removeAttr("disabled");$("#reply-modal").modal("toggle");$(buildCommentHtmlString(appendColNumAndThreadNum(a,b.columnNum,b.threadNum),!0)).insertAfter("#"+a[0].data.parent_id+" .comment-footer:first");externalLinks(".md a");fadeIn($("#"+a[0].data.name),100)}
function externalLinks(a){$(a).each(function(a,c){c.onclick=stopProp;$(c).attr("target","_blank");"/u/"==$(c).attr("href").substring(0,3)||"/r/"==$(c).attr("href").substring(0,3)?$(c).attr("href",window.location.protocol+"//www.reddit.com"+$(c).attr("href")):""})}
function displayComments(a,b){var c=$(".frame-content[data-column="+b+"]");c.children().length?(c=window["firstComment"+b],c!=a[1].data.children[0].data.name&&(c=(new Fn).takeWhile(a[1].data.children,c,function(a,b){return!document.getElementById(a.data.name)&&a.data.name!=b}),$(".frame-content[data-column="+b+"]").prepend(buildCommentHtmlString(c,!0,!0)),c.forEach(function(a){fadeIn($("#"+a.data.name),500)}),0<c.length&&$(".frame-overlay[data-column="+b+"]").launchPopOver(3E3,popOverOptions("bottom",
"",c.length+" new comments!")),markFirstComment(a[1].data.children[0].data.name,b)),updateCommentStats(a[1].data.children),updateCreatedUTC(b)):(c.append(buildCommentHtmlString(a[1].data.children,!0,!0)),fadeIn(c.children(),100));externalLinks(".md a")}function updateCreatedUTC(a){document.getElementsByDataAttribute(".frame-content","data-column",a)[0].getElementsByClassName("time-elapsed").forEach(function(a){a.innerHTML=getTimeElapsed(a.getAttribute("data-created-utc"))})}
function updateCommentStats(a){a.forEach(function(a){var c="more"!=a.kind&&a.data.replies.hasOwnProperty("data")?a.data.replies.data.children:[],d=c.length,e="#"+a.data.name+" .reply-container[data-id="+a.data.name+"]";"undefined"!==typeof a.data.score?$(".score[data-id="+a.data.name+"]").text(a.data.score):void 0;newCommentsOnRefresh(d,a.data.name,e);updateCommentStats(c)})}
function newCommentsOnRefresh(a,b,c){var d=$("#"+b+" .media[data-parentid="+b+"]"),e=$(c+" .reply"),g=$(c+" .reply .reply-num"),f=a-d.length,k=tmpl("tmpl_ab",{newRepliesNum:f}),h=tmpl("tmpl_ac",{replyLength:a,replyText:1<a?"replies":"reply"});0<a&&0<e.length&&a>e.data("replylength")?(e.data("replylength",a),g.text(a),0<f&&0===$(c+" .new-comment").length?$(k).insertAfter(c+" .reply"):(!e.children().length&&0<d.length&&(e.append(h),$(c+".reply .expander").html("&#8722;")),0>=f?void 0:$(c+" .new-comment .diff").text(f+
" new"))):0<a&&0===e.length&&(a=tmpl("tmpl_ad",{name:b,replyLength:a}),$(c).append(a),0<f&&$(k).insertAfter(c+" .reply"),d.hasClass("faded")&&($(c+" .reply").append(h),$(c+" .reply .expander").html("&#8722;")))}function getThreadById(a,b,c,d,e,g,f){genericGet(window.location.protocol+"//www.reddit.com/by_id/t3_"+a+".json",b,c,d,e,g,f)}function getCommentsByLink(a,b,c,d){genericGet(window.location.protocol+"//www.reddit.com/comments/"+a+".json?sort=new",b,c,d)}
function getCommentsById(a,b,c,d,e){genericGet(window.location.protocol+"//www.reddit.com/comments/"+a.substr(3)+"/_/"+b+".json?sort=new",c,d,e)}function getPermalink(a,b){return window.location.protocol+"//www.reddit.com/comments/"+a.substr(3)+"/_/"+b}
function getTimeElapsed(a){if(a){var b=new Date(1E3*a),c=(new Date).getTime(),d=c-b.getTime(),e=Math.floor(d/864E5),d=d-864E5*e,g=Math.floor(d/36E5),d=d-36E5*g,f=Math.floor(d/6E4),d=Math.floor((d-6E4*f)/1E3);return 0!=!e||0>=e?0==e&&0==!g?g.toLocaleString()+"h":0==e&&0==g&&0==!f?f.toLocaleString()+"m":0==e&&0==g&&0==f&&0==!d?d.toLocaleString()+"s":1E3>c-1E3*a?"1s":b.toLocaleTimeString():e.toLocaleString()+"d"}}
function getMergedData(a){var b=[];a.forEach(function(c,d){0<c.length&&(b=b.concat(appendColNumAndThreadNum(c[1].data.children,a[d][2],a[d][3])))});b=b.filter(function(a){if("more"!=a.kind)return a}).sort(byTimeCreated);a[0][1].data.children=b;return a[0]}function byTimeCreated(a,b){return"more"!=a.kind&&"more"==b.kind?1:"more"==a.kind&&"more"!=b.kind?-1:a.data.created_utc<b.data.created_utc?1:a.data.created_utc>b.data.created_utc?-1:0}
function errorPop(a,b){"undefined"!==typeof a&&("timeout"==b?$(a).launchPopOver(3E3,popOverOptions("bottom","Servers Busy","Reddit servers are busy.")):$(a).launchPopOver(3E3,popOverOptions("bottom","Generic Error","There was an error processing this request. Reddit servers could not be reached or are busy. Try refreshing.")))}
function oauthPost(a,b,c,d,e,g){$.ajax({type:"POST",url:a,headers:b,data:c}).done(function(a,b,c){d&&d(a,b,c)}).fail(function(a,b,c){e&&e(a,b,c)}).always(function(){g&&g(c,textStatus,jqXHR)})}function genericGet(a,b,c,d,e,g,f){$.ajax({url:a,type:"GET",timeout:7E3,cache:e||!1}).done(function(a,c,d){b&&b(a,c,d,f)}).fail(function(a,b,d){c&&c(a,b,d,f);errorPop(g,d)}).always(function(){d&&d()})}
function genericPost(a,b,c,d,e,g,f){$.ajax({url:a,type:"POST",timeout:g.timeout||7E3,data:b,cache:!1}).done(function(a,b,d){c&&c(a,b,d,g)}).fail(function(a,b,c){d&&d(a,b,c,g);errorPop(f,c)}).always(function(){e&&e()})}
function getPosts(a,b,c,d){$.ajax({url:window.location.protocol+"//www.reddit.com"+a+"/.json?sort="+b+"&limit="+c+"&jsonp=?",dataType:"json",timeout:7E3,cache:!1}).done(function(a){d.callback(a,d.target)}).fail(function(a,b,c){errorPop(d.errorMsgLoc,c);hideLoader(d.target.columnNum)}).always(function(){d.always&&d.always(d.target)})}
function buildRedditMedia(a,b,c){var d=$("#search-results-container .media-results");!1===c&&d.children().remove();"t3"==b?a.data.children.forEach(function(a,b){d.append(tmpl("tmpl_ao",{obj:a,permalink:a.data.permalink.split("?")[0],timeElapsed:getTimeElapsed(a.data.created_utc),thumbnail:a.data.thumbnail&&"self"!=a.data.thumbnail&&"default"!=a.data.thumbnail?tmpl("tmpl_ao0",{src:window.location.protocol+a.data.thumbnail.substr(5)}):tmpl("tmpl_ap",{})}));fadeIn($("#search-results-container .media-results li:last-child"),
100+50*b,"opacity-7")}):"t5"==b&&a.data.children.forEach(function(a,b){var c=getTimeElapsed(a.data.created_utc);d.append(tmpl("tmpl_aq",{obj:a,timeElapsed:c,subscribers:a.data.subscribers?parseInt(a.data.subscribers).toLocaleString()+" subscribers, a community for "+c:"A community for "+c}));fadeIn($("#search-results-container .media-results li:last-child"),100+50*b,"opacity-7")})}
function buildWatchList(a){var b=a.match,c="",d="";a.subs.forEach(function(a){c+=buildWatchInputOrThreadHtmlString(a,"input")});b.forEach(function(a){d+=buildWatchInputOrThreadHtmlString(a,"input")});$("#watch-subreddits .list-group.contain, #watch-matching .list-group.contain").children().remove();$("#watch-subreddits .list-group.contain").append(c);$("#watch-matching .list-group.contain").append(d)}
function buildRedditConfigObjByThreads(a){var b={},c={},d=[];a.forEach(function(a){var b={};b.subid=a.data.subreddit_id;b.subreddit=a.data.subreddit.toLowerCase();b.thread=a.data.permalink;b.threadid=a.data.id;b.threadtitle=a.data.title;d.push(b)});c.limitPosts="50";c.name=1==a.length?25<a[0].data.title.length?a[0].data.title.trim().substring(0,22)+" ...":a[0].data.title.trim():"My Column";c.refreshRate="60";c.sortBy="new";b.type="reddit";b.settings=c;b.threads=d;return b}
function buildColumn(a,b,c){$(".item[data-column="+b+"]").remove();var d=tmpl("tmpl_i",{num:b}),e=tmpl("tmpl_j",{num:b}),d=tmpl("tmpl_l",{bigButtons:tmpl("tmpl_p",{columnNum:b}),type:"reddit"==a.type?tmpl("tmpl_ired",{}):tmpl("tmpl_itwt",{}),num:b,configObj:a,icons:e,frameContent:d}),d=tmpl("tmpl_m",{frame:d}),d=tmpl("tmpl_n",{num:b,configObj:a,frameContainer:d}),d=tmpl("tmpl_o",{num:b,active:0===b?"active":"",framePosition:d});buildColumnToUI(d,b);buildColumnOptions(a,b,"column");"reddit"==a.type&&
(getCommentsForColumn(a,b,c),toggleRefresh(b));contentResizeEvent();fadeIn(".frame-position[data-column="+b+"]",100)}
function buildCommentHtmlString(a,b,c,d){a=a||[];var e="";a.forEach(function(a){var f="more"!=a.kind&&a.data.replies.hasOwnProperty("data")?a.data.replies.data.children:[],k=f.length,k="more"!=a.kind?tmpl("tmpl_ae",{comment:a,replyLength:k,permalink:getPermalink(a.data.link_id,a.data.id),replies:0!==k?tmpl("tmpl_af",{comment:a,replyLength:k,replyText:1<k?"replies":"reply"}):""}):"",f=$("<div/>").html(a.data.body_html).text()+k+buildCommentHtmlString(f,!0,!1,!0),f="more"!=a.kind?tmpl("tmpl_ag",{comment:a,
text:f,timeElapsed:getTimeElapsed(a.data.created_utc),href:window.location.protocol+"//www.reddit.com/r/"+a.data.subreddit,authorLink:window.location.protocol+"//www.reddit.com/u/"+a.data.author,author:a.data.author,flair:a.data.author_flair_css_class?'<a class="flair btn">'+a.data.author_flair_css_class+"</a>":"&nbsp;"}):tmpl("tmpl_ah",{comment:a,text:f}),f=tmpl("tmpl_ai",{heading:f}),k="more"!=a.kind?tmpl("tmpl_aj",{icon:c?getIcon(a.data.subreddit):""}):"";a=tmpl("tmpl_ak",{comment:a,icon:getIcon(a.data.subreddit),
parent:c?"parent":d?"hide":"",opacity:b?"nopacity":"",thumbnail:k,body:f});e+=a});return e}function buildWatchInputOrThreadHtmlString(a,b){a.timeElapsed=getTimeElapsed(a.created_utc);return"input"==b?tmpl("tmpl_a",{thing:a}):tmpl("tmpl_b",{thing:a})}function buildColumnToUI(a,b){var c=$(".carousel-inner");0===b?0<c.children().length?$(a).insertBefore(".item:first"):c.append(a):$(a).insertAfter($(".item[data-column="+(b-1)+"]"))}
function buildReplyForm(a,b,c){var d=tmpl("tmpl_x",{buttonClass:c?"btn-default":"btn-primary"});a=tmpl("tmpl_y",{thing_id:a});b=tmpl("tmpl_z",{label:c?"<label>Comment</label>":"",placeholder:c?"Write a comment":"Reply to "+b+"..."});return tmpl("tmpl_aa",{className:c?"isTopLevel":"nopacity hide",submitting:c?'<b><span class="black">Submitting...</span></b>':"Submitting...",parentInput:a,textarea:b,buttons:d})}
function buildConfigToUI(a){var b=(new Fn).getFromStorage("config");if(0===b.length)showFeature("#greeting"),0===$("#watch-threads .list-group.contain").children().length?watchList():void 0;else if(showFeature("#content-container"),0===$(".carousel-inner").children().length||a){a&&$(".carousel-inner").children().remove();a=0;for(var c=b.length;a<c;a++)buildColumn(b[a],a,!0)}contentResizeEvent()}
function buildButtons(a){var b="";a.forEach(function(a){b+=tmpl("tmpl_c0",{arrPos0:a[0],arrPos1:a[1],arrPos2:a[2]})});return b}
function buildColumnOptions(a,b){var c=function(){for(var c=tmpl("tmpl_c",{ulClass:"edit-button-group",buttons:buildButtons([["add-thread-button","plus-circle",getPressEvent()+"=\"bindAddThreadButton.call(this, '.edit-form[data-column="+b+"]', 'edit-button-group', 'subreddit-group-edit', 'subreddit-edit', 'thread-edit', 'delete-edit', 'info-edit', "+b+')"'],["cancel-edit-button","close",getPressEvent()+'="bindCancelEdit.call(this, '+b+')"'],["save-edit-button","save",getPressEvent()+'="bindSaveEdit.call(this, '+
b+')"']])}),d=0,e=a.threads.length;d<e;d++)var h=tmpl("tmpl_d",{columnNum:b}),m=tmpl("tmpl_e",{columnNum:b}),h=tmpl("tmpl_f",{subreddit:m,threads:h}),c=c+h;return c}(),d=function(){var a=tmpl("tmpl_c",{ulClass:"edit-button-group",buttons:buildButtons([["cancel-edit-button","close",getPressEvent()+'="bindCancelEdit.call(this, '+b+')"'],["save-edit-button","save",getPressEvent()+'="bindSaveEdit.call(this, '+b+')"']])}),c=$("<div>").append($(".column-settings").children().clone().each(function(){var a=
$(this).find("label"),c=$(this).find("*[id]");a.each(function(a,c){$(c).attr("for",$(c).attr("for")+"-column-"+b)});c.each(function(a,c){$(c).attr("id",$(c).attr("id")+"-column-"+b)})})).html();return tmpl("tmpl_g",{settings:a+c,columnNum:b})}(),e=tmpl("tmpl_am",{})+buildReplyForm("","",!0);$(".edit-form[data-column="+b+"]").append(c);$(".settings-tab[data-column="+b+"]").append(d);$(".write-comment[data-column="+b+"]").append(e);inputLoad(b);setSettingsFromConfig(b,a)}
function bindNewComment(){event.preventDefault();event.stopPropagation();var a=$(this).parents(".media").attr("id"),a=$(".refresh-comment[data-id="+a+"]");bindRefreshComment.call(a)}function bindLoadMore(a,b,c,d){event.preventDefault();var e=$(".media-more li");e.data("after",a);e.data("type",b);e.data("query",c.query);d?e.data("count",25):e.data("count",e.data("count")+25);bindMediaMore(a,b,c)}
function bindMediaMore(a,b,c){$(".media-more li").unbind(getPressEvent().slice(2)).on(getPressEvent().slice(2),function(){event.preventDefault();var a=$(this).data("type"),b="thread"==a?c.url+"?count="+$(this).data("count")+"&after="+$(this).data("after"):c.url+"&count="+$(this).data("count")+"&after="+$(this).data("after");genericGet(b,"thread"==a||"submissions"==a?function(b,e,k,h){h.previousAfter?(threadResults(b,c,!0,a),$("#search-results-container .media[data-id="+h.previousAfter.substr(3)+"]")[0].scrollIntoView(),
bindLoadMore(b.data.after,a,c)):$(".media-more li").unbind("click")}:function(b,e,k,h){h.previousAfter?(subredditsMatching(b,c.query,!0),$("#search-results-container .media[data-id="+h.previousAfter.substr(3)+"]")[0].scrollIntoView(),bindLoadMore(b.data.after,a,c)):$(".media-more li").unbind("click")},void 0,void 0,!1,this,{query:c.query,previousAfter:$(this).data("after")})})}
function bindSubList(){event.preventDefault();copyToAllRedditSearches($(this).data("subreddit"));threadsOfSubreddit($(this).data("subreddit"))}
function bindThreadResults(){event.preventDefault();var a={},b={};b.subreddit_id=$(this).data("subid");b.subreddit=$(this).data("subreddit");b.permalink=$(this).data("thread");b.id=$(this).data("id");b.title=$(this).find("h4").text();a.data=b;addToConfigObj(buildRedditConfigObjByThreads([a]));configObjAction();makeItemActive((new Fn).getFromStorage("config").length-1)}
function bindWatchThreads(){event.preventDefault();$(this).hasClass("white")?$(this).removeClass("white"):$(this).addClass("white")}function bindRedditSignOut(){event.preventDefault();localStorage&&localStorage.removeItem("ruser");updateControlsView()}function bindTwitterSignOut(){event.preventDefault();genericGet("/twitter-logout",function(a){$("[data-twitteruser]").data("twitteruser",null);$("#twitter-logout").replaceWith(a);updateControlsView()})}
function bindRedditLogIn(){window.location="/auth/reddit"}function bindTwitterLogIn(){window.location="/auth/twitter"}function bindSubmitSave(a){event.preventDefault();bindSaveEdit.call($(this.form).find(".save-edit-button"),a)}
function inputLoad(a){event.preventDefault();var b=$(".edit-form[data-column="+a+"] .subreddit-edit"),c=(new Fn).getFromStorage("config");b.each(function(b,e){this.value=c[a].threads[b].subreddit;typeAheadReddit(e,function(b){var c=$(".edit-form[data-column="+a+"] .subreddit-edit").parent().parent().parent().index($(b).parent().parent().parent());getPosts("/r/"+b.value,"","",{target:[".edit-form[data-column="+a+"] .thread-edit",c],errorMsgLoc:b,callback:setThreads})})})}
function bindFetchThreadValue(a){event.preventDefault();if(this.value){var b=$(".edit-form[data-column="+a+"] .subreddit-edit").parent().parent().parent().index($(this).parent().parent().parent());getPosts("/r/"+this.value,"","",{target:[".edit-form[data-column="+a+"] .thread-edit",b],errorMsgLoc:this,callback:setThreads})}}
function bindSaveEdit(a){event.preventDefault();updateConfigObjFromDOM(".column-options[data-column="+a+"] .subreddit-group-edit",".subreddit-edit",".thread-edit",".column-options[data-column="+a+"] .edit-column-settings",a);buildColumn((new Fn).getFromStorage("config")[a],a);makeItemActive(a)}function bindCancelEdit(a){event.preventDefault();showAllColumnOptions(a)}
function bindAddThreadButton(a,b,c,d,e,g,f,k){event.preventDefault();f=tmpl("tmpl_s",{infoClass:f,threadClass:e});g=tmpl("tmpl_t",{input:"'"+a+" ."+d+".tt-input:first'",deleteClass:g,subClass:d,groupClass:"'"+c+"'",threadClass:"'"+e+"'",columnNum:"undefined"!==typeof k?k:!1});g=tmpl("tmpl_u",{groupClass:c,subreddit:g,threads:f});$(g).insertAfter(a+" ."+b);"undefined"!==typeof k?frame_content_height(k):void 0;typeAheadReddit(a+" ."+d+":first",function(b){var d=$(a+" ."+c).index($(b).parent().parent().parent());
getPosts("/r/"+b.value,"","",{target:[a+" ."+e,d],errorMsgLoc:b,callback:setThreads})});fadeIn("."+c,100)}function bindPopulateThreadSelect(a,b,c){event.preventDefault();a=$("."+b).index($(this).parent().parent().parent());getPosts("/r/"+this.value,"","",{target:["."+c,a],errorMsgLoc:this,callback:setThreads})}
function bindInfoThread(a){event.preventDefault();(a=$(this).parents(".form-group").find("select option:selected").data("threadid"))&&getThreadById(a,function(a){a.data.children[0].data.selftext_html?($("#info-title, #info-content").children().remove(),$("#info-title").html(tmpl("tmpl_an",{url:a.data.children[0].data.url,title:a.data.children[0].data.title})),$("#info-content").append($("<div/>").html(a.data.children[0].data.selftext_html).text()),$("#author-button").text("/u/"+a.data.children[0].data.author).attr(getPressEvent(),
"window.open('"+window.location.protocol+"//www.reddit.com/u/"+a.data.children[0].data.author+"','_blank');"),$("#time-button").text(getTimeElapsed(a.data.children[0].data.created_utc)),externalLinks("#info-content .md a"),$("#info-modal").modal()):window.open(a.data.children[0].data.url,"_blank")},void 0,void 0,!0,this)}function bindDeleteThread(a){event.preventDefault();$(this).parent().parent().parent().remove();"undefined"!==typeof a&&frame_content_height(a)}
function bindVoteCast(){event.preventDefault();if(isRedditUserLoggedIn()){var a=$(this).data("id").split("-")[0],b=$(".score[data-id="+$(this).data("id")+"]").data("vote-state"),c=$(this).hasClass("up")?1:-1,b=c==b?0:1==c?1:-1;genericPost("/vote",{id:a,dir:b},function(a,b,c,f){a&&a.needsLogin?$("#login-reddit-modal").modal():a.statusCode?console.log(a.statusCode):a.json&&0<a.json.errors.length?alert(a.json.errors[0][1]):updateVoteState(a,f)},function(a,b,c,f){alert(b+": Couldn't cast vote to "+f.id)},
void 0,{id:a,dir:b})}else $("#login-reddit-modal").modal();(new Fn).getBlurred()}
function bindSaveReply(){event.preventDefault();var a=$(this).parents(".write-comment"),b=this.form?this.form.thing_id.value:$(this).parents(".modal-content").find("form")[0].thing_id.value,c=b.split("-")[0]||"t3_"+a.find(".post-thread option:selected").data("threadid"),b={columnNum:b.split("-")[1]||a.data("column"),threadNum:b.split("-")[2],postPane:0<a.length?a:$(this).parents(".comment-footer"),timeout:99999},d=this.form?this.form.text.value:$(this).parents(".modal-content").find("form")[0].text.value;
0!==d.length&&(this.form?($(this.form.text).attr("disabled","disabled"),$(this).attr("disabled","disabled")):$("#reply-textarea, #reply-save").attr("disabled","disabled"),0<a.length?frame_content_height(b.columnNum):void 0,genericPost("/save-reddit-reply",{thing_id:c,text:d},0<a.length?function(a,b,c,d){a&&a.needsLogin?$("#login-reddit-modal").modal():a.statusCode?topLevelCommentFail(d):a.json&&0<a.json.errors.length?(replyLevelCommentFail(d),alert(a.json.errors[0][1])):postTopLevelComment(a.json.data.things,
d)}:function(a,b,c,d){a&&a.needsLogin?($(".reply-modal").modal(),$("#login-reddit-modal").modal()):a.statusCode?replyLevelCommentFail(d):a.json&&0<a.json.errors.length?(replyLevelCommentFail(d),alert(a.json.errors[0][1])):insertReplyIntoDOM(a.json.data.things,d)},0<a.length?function(a,b,c,d){topLevelCommentFail(d)}:function(a,b,c,d){replyLevelCommentFail(d)},void 0,b))}
function bindTextAreaReply(){event.preventDefault();isRedditUserLoggedIn()?void 0:($(this).parent().parent().hasClass("isTopLevel")||$("#reply-modal").modal("toggle"),$("#login-reddit-modal").modal())}function bindCancelReply(){event.preventDefault();var a=$(this).parents(".comment-footer");0<a.length?bindReplySwitch.call(a.find(".reply-switch")):showAllColumnOptions($(this).parents(".column-options").data("column"))}
function bindReplySwitch(){event.preventDefault();$("#original-comment").children().remove();var a=$(this).parent().parent().data("id"),b=$(".reddit-html[data-id="+a+"]").clone();author=b.data("author");$("#reply-modal").modal("toggle");$("#reply-thing").val(a);$("#original-comment").html(b);$("#reply-title").text(author+" wrote:");$("#reply-textarea").attr("placeholder","Reply to "+author+"...")}
function bindShowReply(){event.preventDefault();event.stopPropagation();var a=$(this).data("name"),a=$("#"+a+" .media[data-parentid="+a+"]"),b=$(this).find(".expander");a.hasClass("hide")?(b.html("&#8722;"),fadeIn(a.removeClass("hide"),100)):(b.html("&#43;"),a.removeClass("faded").addClass("hide"))}
function bindRefreshComment(){event.preventDefault();var a=$(this).data("linkid")||$("#"+$(this).data("parent")).data("linkid"),b=$(this).data("id")||$("#"+$(this).data("parent")).attr("id"),c=$("#"+b).hasClass("parent")||$("#"+$(this).data("parent")).hasClass("parent");getCommentsById(a,b.substr(3).split("-")[0],function(a){var e=b.split("-")[1],g=b.split("-")[2];a=buildCommentHtmlString(appendColNumAndThreadNum(a[1].data.children,e,g));$("#"+b).replaceWith(a);c&&($("#"+b).addClass("parent"),$("#"+
b).children(":first").addClass($("#"+b).data("icon")));$(".reply[data-name="+b+"] .expander").html("&#8722;");$("#"+b+" .media[data-parentid="+$("#"+b).attr("id")+"]").removeClass("hide").addClass("faded");$("#"+b).addClass("nopacity");fadeIn($("#"+b),100);externalLinks(".md a")})}function bindDeleteWatchButtons(){event.preventDefault();$(this).parent().parent().remove()}function bindWatchAddSubreddit(){event.preventDefault();$("#watch-subreddits .list-group.contain").append(tmpl("tmpl_al",{}))}
function bindWatchAddMatching(){event.preventDefault();$("#watch-matching .list-group.contain").append(tmpl("tmpl_al",{}))}function bindWatchRefresh(){event.preventDefault();saveWatchList();watchList()}
function bindWatchSave(){function a(a){return""!==$(a).val()}event.preventDefault();var b=new Fn,c=$("#watch-subreddits .list-group.contain"),d=$("#watch-matching .list-group.contain");if(0!==c.children().length&&b.any(c.find("input"),a)&&0!==d.children().length&&b.any(d.find("input"),a)){if(saveWatchList(),$(this).hasClass("wthreads"))if(b.any("#watch-threads .list-group.contain li",function(a){return $(a).hasClass("white")})){var e=[];$("#watch-threads .list-group.contain li.white").each(function(a,
b){var c={},d={};d.subreddit_id=$(b).data("subid");d.subreddit=$(b).data("subreddit");d.permalink=$(b).data("thread");d.id=$(b).data("threadid");d.title=$(b).text();c.data=d;e.push(c)});addToConfigObj(buildRedditConfigObjByThreads(e));configObjAction();makeItemActive(b.getFromStorage("config").length-1)}else $("#watch-threads .list-group-item.controls").launchPopOver(3E3,popOverOptions("top","Verification","Please select at least one thread from the list."))}else $("#watch-subreddits .list-group-item.controls, #watch-matching .list-group-item.controls, #watch-threads .list-group-item.controls").launchPopOver(3E3,
popOverOptions("top","Verification","Verify you have one subreddit and one matching pattern added with values."))}function bindDeleteColumn(){var a=new Fn,b=a.getFromStorage("config"),c=$(this).data("column");b.forEach(function(a,b){deleteRefresh(b)});a.remove(b,c);a.setInStorage("config",b);delete window["firstComment"+c];buildConfigToUI(!0);$("#delete-column-modal").modal("hide")}
function bindAutoRefreshActive(){event.preventDefault();$("#carousel").unbind("slid.bs.carousel").on("slid.bs.carousel",function(){autoRefreshOnlyActiveColumn()})}function bindColumnButton(){0<(new Fn).getFromStorage("config").length?buildConfigToUI():$(this).parent().launchPopOver(3E3,popOverOptions("top","No columns","Build at least one column to view columns."))}function bindHomeButton(){0===$("#watch-threads .list-group.contain").children().length?watchList():"";showFeature("#greeting")}
function bindRedditSearchRadio(){var a=$(this).parents("form").find("select");"submissions"==$(this).parents("form").find("input[type=radio]:checked").val()?a.removeAttr("disabled"):a.attr("disabled",!0)}function bindSaveChanges(){addColumnToConfig()?(buildConfigToUI(!0),makeItemActive((new Fn).getFromStorage("config").length-1)):buildConfigToUI();$(".sub-group-controls").remove();$("#controls").modal("hide")}
function bindPreventEnterButton(){if(13==event.which){var a=new Fn;event.preventDefault();a.getBlurred();$(this).parent().parent().parent().find("select").focus()}}
function bindRedditSearch(a){event.preventDefault();var b=$(this.form).find(".reddit-search-input.tt-input").val(),c=new Fn;if(b){$("#controls").modal("hide");var d=$(this.form).find("input[type=radio]:checked").val(),e=$(this.form).find("select.sorted-by").val(),g=$(this.form).find("select.links-from").val();"subreddits"==d?subredditsSearchAPI({query:b,errorLoc:$(this.form).find(".reddit-search-input.tt-input")}):submissionsSearchAPI({query:b,sorted_by:e,links_from:g,errorLoc:$(this.form).find(".reddit-search-input.tt-input"),
callback:a})}c.getBlurred()}function bindRefreshCommentSwitch(a){event.preventDefault();var b=$(this).find("i");b.toggleClass("fa-toggle-on fa-toggle-off");b.hasClass("fa-toggle-on")&&getCommentsForColumn((new Fn).getFromStorage("config")[a],a);toggleRefresh(a)}function bindGetCommentsForColumn(a){event.preventDefault();getCommentsForColumn((new Fn).getFromStorage("config")[a],a)}
function bindColumnBars(a){event.preventDefault();var b=$(".column-options[data-column="+a+"]");b.hasClass("hide")?(b.removeClass("hide"),column_options_height(a),frame_content_height(),$(".edit-form[data-column="+a+"] .subreddit-group-edit").each(function(a){var b=$(this).find(".subreddit-edit.tt-input").val(),e=$(this).find(".thread-edit"),g=e.val(),e=e.data("column");""!==b&&null===g&&getPosts("/r/"+b,"","",{target:[".edit-form[data-column="+e+"] .thread-edit",a,e],errorMsgLoc:this,callback:setThreads})})):
(showAllColumnOptions(a),b.addClass("hide"),column_options_height(a,0))}function bindManageThreads(a){event.preventDefault();var b=$(".edit-form[data-column="+a+"]");$(this.nextElementSibling).hasClass("hide")?showColumnOption(b,a):showAllColumnOptions(a);frame_content_height(a)}function bindSettings(a){event.preventDefault();var b=$(".settings-tab[data-column="+a+"]");$(this.nextElementSibling).hasClass("hide")?showColumnOption(b,a):showAllColumnOptions(a)}
function bindWriteComment(a){event.preventDefault();var b=$(".write-comment[data-column="+a+"]");setPostThreads(".write-comment[data-column="+a+"]",".edit-form[data-column="+a+"]");$(this.nextElementSibling).hasClass("hide")?showColumnOption(b,a):showAllColumnOptions(a);frame_content_height(a)}
function bindDeleteColumnButton(a){event.preventDefault();$("#delete-column").data("column",a);$("#column-to-delete").text((new Fn).getFromStorage("config")[a].settings.name);$("#delete-column-modal").modal()}function bindHelpModal(){$("#help-modal").modal("show")}function bindToggleCommentOptions(){var a=$(this).parents(".media-body:first").find("header:first, footer:first"),b=a.hasClass("hide");$(".media-body header, .media-body footer").addClass("hide");b&&a.removeClass("hide")}
function stopProp(a){a.stopPropagation()};(function(a,b,c,d,e,g,f){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;g=b.createElement(c);f=b.getElementsByTagName(c)[0];g.async=1;g.src=d;f.parentNode.insertBefore(g,f)})(window,document,"script","//www.google-analytics.com/analytics.js","ga");ga("create","UA-57745225-1","auto");ga("send","pageview");
